### ISSUE TITLE
最新小蚁摄像机最新固件运行main.py报错

### ISSUE THREAD

**Issue by leangjia** [yefei/xiaoyi_camera_video_download#1]
小蚁摄像机已经更新为今日最新固件。
报错如下：
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
liang＊＊＊@server:~/git$ git clone https://github.com/yefei/xiaoyi_camera_video_download
正克隆到 'xiaoyi_camera_video_download'...
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 11 (delta 1), reused 11 (delta 1), pack-reused 0
Unpacking objects: 100% (11/11), done.
检查连接... 完成。
liang＊＊＊@server:~/git$ ls
dolibarr  greenodoo  opencart       transifex-client
Git教程   odoo       openerp-china  xiaoyi_camera_video_download
liang＊＊＊@server:~/git$ cd xiaoyi_camera_video_download
liang＊＊＊@server:~/git/xiaoyi_camera_video_download$ ls
cam-ip.txt  last-date.txt  main.py  README.md
liangj＊＊＊@server:~/git/xiaoyi_camera_video_download$ gedit cam-ip.txt
liang＊＊＊@server:~/git/xiaoyi_camera_video_download$ ls
cam-ip.txt  cam-ip.txt~  last-date.txt  main.py  README.md
liang＊＊＊@server:~/git/xiaoyi_camera_video_download$ ls -l
总用量 16
-rw-rw-r-- 1 liang＊＊＊ liang＊＊＊   15  2月  4 16:09 cam-ip.txt
-rw-rw-r-- 1 liang＊＊＊ liang＊＊＊    0  2月  4 16:06 cam-ip.txt~
-rw-rw-r-- 1 liang＊＊＊ liang＊＊＊    1  2月  4 16:06 last-date.txt
-rw-rw-r-- 1 liang＊＊＊ liang＊＊＊ 3280  2月  4 16:06 main.py
-rw-rw-r-- 1 liang＊＊＊ liang＊＊＊  500  2月  4 16:06 README.md
liangjia@server:~/git/xiaoyi_camera_video_download$ py main.py
py：未找到命令
liang＊＊＊@server:~/git/xiaoyi_camera_video_download$ main.py
main.py：未找到命令
liang＊＊＊@server:~/git/xiaoyi_camera_video_download$ python main.py
摄像机IP: 192.168.43.213

创建存储目录: videos
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    paths = get_record_paths(cam_ip)
  File "main.py", line 37, in get_record_paths
    data = get_url_content('http://%s/sd/record/' % cam_ip)
  File "main.py", line 32, in get_url_content
    response = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
liang＊＊＊@server:~/git/xiaoyi_camera_video_download$ chmod a+x main.py
liang＊＊＊@server:~/git/xiaoyi_camera_video_download$ python main.py
摄像机IP: 192.168.43.213

Traceback (most recent call last):
  File "main.py", line 82, in <module>
    paths = get_record_paths(cam_ip)
  File "main.py", line 37, in get_record_paths
    data = get_url_content('http://%s/sd/record/' % cam_ip)
  File "main.py", line 32, in get_url_content
    response = urllib2.urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
liang＊＊＊@server:~/git/xiaoyi_camera_video_download$ sudo su

请问是一定需要root权限还是其他呢？打扰您　了。

**Comment by d3v-ana** [comment]
最重要的就是最后一句话吧，
urllib2.HTTPError: HTTP Error 403: Forbidden
小米在固件中关闭了网页方式下载录像功能，所以不能通过url来访问内存卡中的视频。

**Comment by leangjia** [comment]
谢谢，小蚁摄像机已经卖掉了。
